import { VibeState } from "./types";

interface ContextBundle {
  task: string;
  relevantRequirements: { id: string; text: string }[];
  relevantDecisions: { id: string; title: string; decision: string }[];
  relevantConstraints: { id: string; text: string; severity: string }[];
  relevantFiles: string[];
}

function score(text: string, keywords: string[]): number {
  const lower = text.toLowerCase();
  return keywords.reduce((acc, kw) => (lower.includes(kw) ? acc + 1 : acc), 0);
}

function extractKeywords(task: string): string[] {
  return task
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, " ")
    .split(/\s+/)
    .filter((w) => w.length > 3);
}

export function buildContext(state: VibeState, task: string): ContextBundle {
  const keywords = extractKeywords(task);

  const relevantRequirements = state.requirements
    .map((r) => ({ r, s: score(r.text + " " + r.tags.join(" "), keywords) }))
    .filter((x) => x.s > 0)
    .sort((a, b) => b.s - a.s)
    .slice(0, 5)
    .map((x) => ({ id: x.r.id, text: x.r.text }));

  const relevantDecisions = state.decisions
    .map((d) => ({ d, s: score(d.title + " " + d.decision + " " + d.context, keywords) }))
    .filter((x) => x.s > 0)
    .sort((a, b) => b.s - a.s)
    .slice(0, 5)
    .map((x) => ({ id: x.d.id, title: x.d.title, decision: x.d.decision }));

  const relevantConstraints = state.constraints
    .map((c) => ({ c, s: score(c.text, keywords) }))
    .filter((x) => x.s > 0)
    .map((x) => ({ id: x.c.id, text: x.c.text, severity: x.c.severity }));

  const relevantFiles = Array.from(
    new Set(
      state.requirements
        .filter((r) => relevantRequirements.some((rr) => rr.id === r.id))
        .flatMap((r) => r.linkedFiles)
    )
  );

  return { task, relevantRequirements, relevantDecisions, relevantConstraints, relevantFiles };
}

export function renderAgentsMd(state: VibeState, bundle: ContextBundle): string {
  const lines: string[] = [];
  lines.push(`# AI Agent Context — ${state.project.name}`);
  lines.push("");
  lines.push(`> Generated by VIBE on ${new Date().toISOString()}. Treat this as the current source of truth for scope.`);
  lines.push("");
  lines.push(`## Current Task`);
  lines.push(bundle.task);
  lines.push("");
  if (bundle.relevantRequirements.length) {
    lines.push(`## Relevant Requirements`);
    for (const r of bundle.relevantRequirements) lines.push(`- **${r.id}**: ${r.text}`);
    lines.push("");
  }
  if (bundle.relevantDecisions.length) {
    lines.push(`## Relevant Architecture Decisions`);
    for (const d of bundle.relevantDecisions) lines.push(`- **${d.id}** (${d.title}): ${d.decision}`);
    lines.push("");
  }
  if (bundle.relevantConstraints.length) {
    lines.push(`## Constraints`);
    for (const c of bundle.relevantConstraints) lines.push(`- [${c.severity.toUpperCase()}] ${c.text}`);
    lines.push("");
  }
  if (bundle.relevantFiles.length) {
    lines.push(`## Files Likely In Scope`);
    for (const f of bundle.relevantFiles) lines.push(`- ${f}`);
    lines.push("");
  }
  lines.push(`## Ground Rules`);
  lines.push(`- Stay within the files/requirements listed above unless the task clearly requires more.`);
  lines.push(`- If you must deviate from a listed architecture decision, flag it — don't silently override it.`);
  lines.push(`- After making changes, the developer will run \`vibe guard\` to check scope/impact before merging.`);
  return lines.join("\n");
}
